### ISSUE TITLE
Invalid maximum heap size

### ISSUE THREAD

**Issue by JCTRoth** [swimlane/elk-tls-docker#11]
**Elasticsearch container:**
Invalid maximum heap size: -Xmx"2g"
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Logstash Container:**
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid maximum heap size: -Xmx"1g"
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I had run the following command before starting up container:
`sudo sysctl -w vm.max_map_count=562144`

```
# Configuration Variables
ELASTICSEARCH_HEAP="2g"
LOGSTASH_HEAP="1g"
PACKETBEAT_HEAP="256m"
FILEBEAT_HEAP="256m"
METRICBEAT_HEAP="256m"
```

**Comment by yagely80** [comment]
you just need to remove the " in the env file.

**Comment by JCTRoth** [comment]
```
ELK_VERSION=7.12.0
ELASTIC_USERNAME=elastic
ELASTIC_PASSWORD=XXXXXXXXXX

# Configuration Variables
ELASTICSEARCH_HEAP=3g
LOGSTASH_HEAP=1g
PACKETBEAT_HEAP=256m
FILEBEAT_HEAP=256m
METRICBEAT_HEAP=256m
XPACK_ENCRYPTION_KEY=XXXXXXXXXXXXXXXXXXXXXXXX

# Self signed TLS certificates
CA_PASSWORD=
CA_DAYS=3650
ELASTIC_DIR=/usr/share/elasticsearch
LOGSTASH_DIR=/usr/share/logstash
KIBANA_DIR=/usr/share/kibana
PACKETBEAT_DIR=/usr/share/packetbeat
FILEBEAT_DIR=/usr/share/filebeat
METRICBEAT_DIR=/usr/share/metricbeat

# Letsencrypt certificates
## Setting STAGING to true means it will generate self-signed certificates
## Setting STAGING to false means it will generate letsencrypt certificates
# STAGING=false
STAGING=true

# swag Configuration
DOMAIN=XXXXXXXXXX
#SUBDOMAIN=kibana
#SUBFOLDER=kibana
EMAIL=info@mailbase.info
TIMEZONE=Germany/Berlin
```

Works like this.
Should I change Doc and .env-example and create a merge request ?

**Comment by MSAdministrator** [comment]
@JCTRoth yes that would be great! Thanks!

**Comment by MSAdministrator** [comment]
This has been resolved.
