### ISSUE TITLE
Issues running docker-compose.production.yml 

### ISSUE THREAD

**Issue by rbcrack** [swimlane/elk-tls-docker#13]
I have followed the instruction on what ned to be changed in swage and I am getting an error 

ERROR: for elasticsearch  Cannot create container for service elasticsearch: invalid mount config for type "bind": bind source path does not exist: /home/elog/elk-tls-docker/secrets/ca/ca.crt

ERROR: for elasticsearch  Cannot create container for service elasticsearch: invalid mount config for type "bind": bind source path does not exist: /home/elog/elk-tls-docker/secrets/ca/ca.crt

![image](https://user-images.githubusercontent.com/18475926/121594302-bff8ff80-c9f1-11eb-9018-362bd2286b14.png)

**Comment by rbcrack** [comment]
The test environment works fine

**Comment by rbcrack** [comment]
In test env I keep getting this 
![image](https://user-images.githubusercontent.com/18475926/121599499-f9cd0480-c9f7-11eb-951e-241fa3e42a77.png)

**Comment by MSAdministrator** [comment]
@rbcrack after setting those values in the .env did you rerun this command?

docker-compose -f docker-compose.setup.yml run --rm certs

**Comment by rbcrack** [comment]
Yes and all went good only the second command fails

**Comment by rbcrack** [comment]
> @rbcrack after setting those values in the .env did you rerun this command?
> 
> docker-compose -f docker-compose.setup.yml run --rm certs

This what I get 


root@elog:/home/elog/elk-tls-docker# docker-compose -f docker-compose.setup.yml run --rm certs
WARNING: The SUBFOLDER variable is not set. Defaulting to a blank string.
CentOS Linux 8 - AppStream                                                                                                                                                                                   8.9 MB/s | 7.4 MB     00:00
CentOS Linux 8 - BaseOS                                                                                                                                                                                      2.2 MB/s | 2.6 MB     00:01
CentOS Linux 8 - Extras                                                                                                                                                                                       22 kB/s | 9.6 kB     00:00
Last metadata expiration check: 0:00:01 ago on Fri Jun 11 22:21:54 2021.
Package unzip-6.0-43.el8.x86_64 is already installed.
Package openssl-1:1.1.1g-15.el8_3.x86_64 is already installed.
Dependencies resolved.
=============================================================================================================================================================================================================================================
 Package                                                Architecture                                            Version                                                        Repository                                               Size
=============================================================================================================================================================================================================================================
Upgrading:
 unzip                                                  x86_64                                                  6.0-44.el8                                                     baseos                                                  195 k

Transaction Summary
=============================================================================================================================================================================================================================================
Upgrade  1 Package

Total download size: 195 k
Downloading Packages:
unzip-6.0-44.el8.x86_64.rpm                                                                                                                                                                                  471 kB/s | 195 kB     00:00
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                        387 kB/s | 195 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                                                     1/1
  Upgrading        : unzip-6.0-44.el8.x86_64                                                                                                                                                                                             1/2
  Cleanup          : unzip-6.0-43.el8.x86_64                                                                                                                                                                                             2/2
  Running scriptlet: unzip-6.0-43.el8.x86_64                                                                                                                                                                                             2/2
  Verifying        : unzip-6.0-44.el8.x86_64                                                                                                                                                                                             1/2
  Verifying        : unzip-6.0-43.el8.x86_64                                                                                                                                                                                             2/2

Upgraded:
  unzip-6.0-44.el8.x86_64

Complete!
====== Removing Existing Secrets ======
=====================================================
Removing file /secrets/bundle.zip
Removing file /secrets/cert_keystores.zip
Removing directory /secrets/certificate_authority
Removing directory /secrets/certificates
Removing file /secrets/elasticsearch.keystore
Removing directory /secrets/keystores
====== Creating Required Directories ======
=====================================================
Creating Certificate Authority Directory...
Creating Keystores Directory...
Creating Certificates Directory...
========== Creating Elasticsearch Keystore ==========
=====================================================
Setting bootstrap password...
Saving new elasticsearch.keystore
======= Keystore setup completed successfully =======
=====================================================
====== Creating Self-Signed Certificate Authority ======
=====================================================
Generating Self-Signed Certificate Authority PEM ...
Archive:  /secrets/certificate_authority/ca.zip
   creating: /secrets/certificate_authority/ca/
  inflating: /secrets/certificate_authority/ca/ca.crt
  inflating: /secrets/certificate_authority/ca/ca.key
Generating Self-Signed Certificate Authority P12 ...
elastic-stack-ca.p12 is located /secrets/certificate_authority/elastic-stack-ca.p12
====== Generating Certiticate Keystores ======
=====================================================
Creating p12 certificate keystores
Archive:  /secrets/cert_keystores.zip
   creating: /secrets/keystores/elasticsearch/
  inflating: /secrets/keystores/elasticsearch/elasticsearch.p12
   creating: /secrets/keystores/kibana/
  inflating: /secrets/keystores/kibana/kibana.p12
   creating: /secrets/keystores/logstash/
  inflating: /secrets/keystores/logstash/logstash.p12
   creating: /secrets/keystores/filebeat/
  inflating: /secrets/keystores/filebeat/filebeat.p12
   creating: /secrets/keystores/metricbeat/
  inflating: /secrets/keystores/metricbeat/metricbeat.p12
   creating: /secrets/keystores/packetbeat/
  inflating: /secrets/keystores/packetbeat/packetbeat.p12
Creating crt and key certificates
Archive:  /secrets/bundle.zip
   creating: /secrets/certificates/elasticsearch/
  inflating: /secrets/certificates/elasticsearch/elasticsearch.crt
  inflating: /secrets/certificates/elasticsearch/elasticsearch.key
   creating: /secrets/certificates/kibana/
  inflating: /secrets/certificates/kibana/kibana.crt
  inflating: /secrets/certificates/kibana/kibana.key
   creating: /secrets/certificates/logstash/
  inflating: /secrets/certificates/logstash/logstash.crt
  inflating: /secrets/certificates/logstash/logstash.key
   creating: /secrets/certificates/filebeat/
  inflating: /secrets/certificates/filebeat/filebeat.crt
  inflating: /secrets/certificates/filebeat/filebeat.key
   creating: /secrets/certificates/metricbeat/
  inflating: /secrets/certificates/metricbeat/metricbeat.crt
  inflating: /secrets/certificates/metricbeat/metricbeat.key
   creating: /secrets/certificates/packetbeat/
  inflating: /secrets/certificates/packetbeat/packetbeat.crt
  inflating: /secrets/certificates/packetbeat/packetbeat.key
PLEASE RUN DOCKER-COMPOSE.PRODUCTION.YML TO COMPLETE SETUP!
=====================================================
SSL Certificates generation completed successfully.
=====================================================
root@elog:/home/elog/elk-tls-docker# docker-compose -f docker-compose.production.yml up
WARNING: Service "elasticsearch" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/ca/ca.crt", the following file should be created "/home/elog/elk-tls-docker/secrets/ca/ca.crt"
WARNING: Service "elasticsearch" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/elasticsearch/elasticsearch.crt", the following file should be created "/home/elog/elk-tls-docker/secrets/elasticsearch/elasticsearch.crt"
WARNING: Service "elasticsearch" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/elasticsearch/elasticsearch.key", the following file should be created "/home/elog/elk-tls-docker/secrets/elasticsearch/elasticsearch.key"
WARNING: Service "kibana" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/ca/ca.crt", the following file should be created "/home/elog/elk-tls-docker/secrets/ca/ca.crt"
WARNING: Service "kibana" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/kibana/kibana.crt", the following file should be created "/home/elog/elk-tls-docker/secrets/kibana/kibana.crt"
WARNING: Service "kibana" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/kibana/kibana.key", the following file should be created "/home/elog/elk-tls-docker/secrets/kibana/kibana.key"
WARNING: Service "logstash" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/ca/ca.crt", the following file should be created "/home/elog/elk-tls-docker/secrets/ca/ca.crt"
WARNING: Service "logstash" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/logstash/logstash.crt", the following file should be created "/home/elog/elk-tls-docker/secrets/logstash/logstash.crt"
WARNING: Service "logstash" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/logstash/logstash.key", the following file should be created "/home/elog/elk-tls-docker/secrets/logstash/logstash.key"
WARNING: Service "logstash" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/logstash/logstash.pkcs8.key", the following file should be created "/home/elog/elk-tls-docker/secrets/logstash/logstash.pkcs8.key"
WARNING: Service "packetbeat" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/ca/ca.crt", the following file should be created "/home/elog/elk-tls-docker/secrets/ca/ca.crt"
WARNING: Service "filebeat" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/ca/ca.crt", the following file should be created "/home/elog/elk-tls-docker/secrets/ca/ca.crt"
WARNING: Service "filebeat" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/filebeat/filebeat.crt", the following file should be created "/home/elog/elk-tls-docker/secrets/filebeat/filebeat.crt"
WARNING: Service "filebeat" uses an undefined secret file "/home/elog/elk-tls-docker/secrets/filebeat/filebeat.key", the following file should be created "/home/elog/elk-tls-docker/secrets/filebeat/filebeat.key"
WARNING: Found orphan containers (metricbeat, elastic-agent) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Recreating elasticsearch ... error

ERROR: for elasticsearch  Cannot create container for service elasticsearch: invalid mount config for type "bind": bind source path does not exist: /home/elog/elk-tls-docker/secrets/ca/ca.crt

ERROR: for elasticsearch  Cannot create container for service elasticsearch: invalid mount config for type "bind": bind source path does not exist: /home/elog/elk-tls-docker/secrets/ca/ca.crt
ERROR: Encountered errors while bringing up the project.
root@elog:/home/elog/elk-tls-docker#

**Comment by MSAdministrator** [comment]
Okay I think I know what’s going on. Let push an update this evening.

**Comment by hirisov** [comment]
Any updates on this? It gives the same error for me today as well.

**Comment by MSAdministrator** [comment]
This has been resolved

**Comment by rbcrack** [comment]
Now getting this new error after updating the yml file

ERROR: Service "logstash" uses an undefined secret "logstash.pkcs8"

**Comment by rbcrack** [comment]
> This has been resolved

Gettting this error after the update 

ERROR: Service "logstash" uses an undefined secret "logstash.pkcs8"

**Comment by thetractor** [comment]
@rbcrack the problem is that the secret is named ` logstash.pkcs8.key` and the logstash service references it with ` logstash.pkcs8`. 

You have to change https://github.com/swimlane/elk-tls-docker/blob/fe774b34484a3615938a450daebf82a3fabf24e7/docker-compose.production.yml#L163 to `- source: logstash.pkcs8.key`
