### ISSUE TITLE
Issue with generating certificates

### ISSUE THREAD

**Issue by XXXereXXX** [swimlane/elk-tls-docker#6]
Hello There!

I ran into an issue while setting up certificates.
here is my ERROR:
`WARNING: The SUBFOLDER variable is not set. Defaulting to a blank string.
Creating elk-stack_certs_run ... done
/usr/share/elasticsearch/config/setup.sh: /usr/share/elasticsearch/config/setup.sh: Is a directory
ERROR: 126`

I tried to solve it by amending my configuration but I could not.
now I can't even set it up by your default configuration neither.(same issue happens)
please help!

**Comment by MSAdministrator** [comment]
Can you provide your .env configuration (please modify any sensitive information)

**Comment by XXXereXXX** [comment]
Thanks for response!
RAM = 16G
.env:

ELK_VERSION=7.11.1
ELASTIC_USERNAME="elastic"
ELASTIC_PASSWORD="Th15_15_4_57ron9_passworD"

# Configuration Variables
ELASTICSEARCH_HEAP="4g"
LOGSTASH_HEAP="2g"
PACKETBEAT_HEAP="512m"
FILEBEAT_HEAP="512m"
XPACK_ENCRYPTION_KEY="2welkrfj943tngs5fkv9824fm9vwriMQBbtsynu4bV2uxLy"

# Self signed TLS certificates
CA_PASSWORD="L37_u5_encryp7_It_Bro"
CA_DAYS=3650
ELASTIC_DIR=/usr/share/elasticsearch
LOGSTASH_DIR=/usr/share/logstash
KIBANA_DIR=/usr/share/kibana
PACKETBEAT_DIR=/usr/share/packetbeat
FILEBEAT_DIR=/usr/share/filebeat

# Letsencrypt certificates
## Setting STAGING to true means it will generate self-signed certificates
## Setting STAGING to false means it will generate letsencrypt certificates
# STAGING=false
STAGING=true

# swag Configuration
#DOMAIN=company.us
#SUBDOMAIN=kibana
#SUBFOLDER=kibana
#EMAIL=email@company.us
TIMEZONE=America/Chicago
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
docker-compose.setup.yml is default
