### ISSUE TITLE
Basic License 

### ISSUE THREAD

**Issue by XXXereXXX** [swimlane/elk-tls-docker#9]
Hi everyone

I tried to change license type to 'Basic' in **elasticsearch/config/elasticsearch.yml** file but I found this log in elasticsearch container:
 
`{"type":` "server", "timestamp": "2021-05-22T06:24:11,812Z", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "message": "license [92248c89-3ac2-4729-b73a-1611606a09e6] mode [trial] - valid", "cluster.uuid": "uM8gkmVjSj2ghP8eM3sJlA", "node.id": "YzNhrfDCRH-46DRq-E8MfA"  }
{"type": "server", "timestamp": "2021-05-22T06:24:11,814Z", "level": "INFO", "component": "o.e.x.s.s.SecurityStatusChangeListener", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "message": "Active license is now [TRIAL]; Security is enabled", "cluster.uuid": "uM8gkmVjSj2ghP8eM3sJlA", "node.id": "YzNhrfDCRH-46DRq-E8MfA"  }`

Can you help me to have this ELK with basic license?

**Comment by MSAdministrator** [comment]
Hey @XXXereXXX that is currently not a setting available in the .env but you can change your value : https://github.com/swimlane/elk-tls-docker/blob/master/elasticsearch/config/elasticsearch.yml#L7

**Comment by XXXereXXX** [comment]
Hey thanks for your response.
I had mistakenly written ".env" but I edited my post immediately, changing it to "elasticsearch.yml". donno where you read it :D
I had made changes to "elasticsearch.yml" file.
here is all configurations in the file.(I made some other changes too)
![Screenshot from 2021-05-23 08-40-48](https://user-images.githubusercontent.com/73839920/119247887-9c852680-bba2-11eb-812f-e2120d4d6e1c.png)

**Comment by MSAdministrator** [comment]
@XXXereXXX i saw it in my email first but that’s weird you’re still getting that after setting it to basic. (https://www.elastic.co/guide/en/elasticsearch/reference/current/license-settings.html).

maybe try and rebuild.

run 

docker-compose up —build —remove-orphans

let me know if that fixes it or not.

**Comment by XXXereXXX** [comment]
Honestly, I reinstalled my OS (as it performed weird in all tasks :D) (CentOS -> Ubuntu).
now everything works fine.

**Comment by jjjan** [comment]
I have this issue after 30 days the license goes from basic to trail and every things fucked up. I can't login to Kibana. as license for elk change from elastic search need attention very serious.

**Comment by xerxes0x0a** [comment]
ELK stack generates errors regarding license a lot.
every time I rebuild it and it works for some days. I haven't found any permanent solution
